@startuml
actor Оператор

participant "API" as API
participant "MQ" as MQ
participant "Redis" as Cache
participant "БД" as DB

Оператор -> API : Запрос на чтение списка заказов
API -> Cache : Запрос данных в кэш
alt Данные есть в кэше
    Cache -> API : Данные из кэша
else Данные отсутствуют в кэше
    API -> DB : Запрос данных
    DB -> API : Данные из БД
    "API" -> Cache : Запись данных в кэш
end
"API" -> Оператор : Список заказов

group Изменение статуса заказа
    Оператор -> API : Запрос на изменение статуса заказа
    API -> MQ : Отправка запроса на изменение статуса заказа в очередь
    API -> Оператор : Запрос принят
    Оператор -> API : Подписка на события SSE

    group Асинхронная обработка
        API -> MQ : Чтение запроса на изменение статуса заказа

        API -> Cache : Обновление данных в кэше
        API -> Db : Обновление данных в БД
        alt Ошибка при обращении к БД
            API -> Cache : Откат изменений в кэше
            API -> Оператор : оповещение о неуспешном завершении операции
        else Иначе
            API -> Оператор : оповещение об успешном завершении операции
        end
    end
end
@enduml