@startuml
actor Оператор

participant "API" as API
participant "Redis" as Cache
participant "БД" as DB

Оператор -> API : Запрос на чтение списка заказов
API -> Cache : Запрос данных в кэш
alt Данные есть в кэше
    Cache -> API : Данные из кэша
else Данные отсутствуют в кэше
    API -> DB : Запрос данных
    DB -> API : Данные из БД
    "API" -> Cache : Запись данных в кэш
end
"API" -> Оператор : Список заказов

Оператор -> API : Изменение статуса заказа
alt Данные есть в кэше
    API -> Cache : Обновление данных
end
@enduml